### ISSUE TITLE
Gh-pages wiki link

### ISSUE THREAD

**Issue by liuvictoria** [gchure/reproducible_research#1]
I was looking at the wiki page for the reproducible_website template (the gh_pages branch), and I was trying to click on “Adding a new page” under “Customization.” However, when I clicked on it, it linked me to “Changing the color scheme,” and I couldn’t seem to find information about how to add a new page. Here is a screenshot of my issue. Thank you!
![image](https://user-images.githubusercontent.com/66798771/86029393-19466980-ba01-11ea-8a6b-45cf62ed5dbc.jpeg)

**Comment by gchure** [comment]
This issue corresponds to the [sibling repository](https://github.com/gchure/reprorducible_website). I will deal with it over there. Closing for now.
